### ISSUE TITLE
Feature Request: Skills/Proficiencies Tab

### ISSUE THREAD

**Issue by ditzer252** [mclemente/party-overview#16]
As a GM for PF2e, it would be handy to see all PC's skill training and proficiency modifiers.
Thanks!

**Comment by mclemente** [comment]
Sorry for leaving this hanging without a proper answer, but the window doesn't look good with 16+ items showing. See how it looks in dnd5e, with 18 skills for 4 types of proficiencies (none, half-proficient, proficient, expertise).
![image](https://user-images.githubusercontent.com/5288872/148432831-922afe1f-b9ce-463c-bf44-7e38853b42eb.png).
Now imagine that with U/T/E/M/L or the words actually spelled out and with modifiers.

I might give this a try later with some kind of filter for the attributes or separate them in more than one tab so that it doesn't look bad.

**Comment by ditzer252** [comment]
yeah, I can see now that its not easy.  Thanks for considering it. :)

**Comment by tagnullde** [comment]
While you at it, maybe consider adding tool proficiencies (dnd5e) to your addon too?

**Comment by mclemente** [comment]
Need some opinion on how "readable at a glance" this is:

Initial View:

![image](https://user-images.githubusercontent.com/5288872/149687421-465c1ad3-02e0-4b87-a404-95c85f7b6c91.png)

Expanding the width:

![image](https://user-images.githubusercontent.com/5288872/149687637-b84f15f4-f7c8-4429-be89-72665e7c8238.png)

**Comment by ditzer252** [comment]
Thanks for sharing your progress.  It's a lot, not very readable to be honest.  Would it be possible to transpose the columns and rows in your app?
________________________________

**Comment by mclemente** [comment]
> Would it be possible to transpose the columns and rows in your app?

OMG, why I haven't thought of that before?

Here's some options:

Bold Colored numbers (colors might be a bit hard to see):
![image](https://user-images.githubusercontent.com/5288872/149773829-836633fc-0140-4469-8410-3b841bfd2d7e.png)

Colored background, white numbers:
![image](https://user-images.githubusercontent.com/5288872/149774150-4c369e95-647b-41da-94ce-2800653477ae.png)

This one is just awful, just for the sake of "what if?"
![image](https://user-images.githubusercontent.com/5288872/149774246-30658232-cc6e-4b7c-9680-b5a802d2fa5c.png)

**Comment by ditzer252** [comment]
Wow! This is quite nice.  I think the colored background is the best presentation.

**Comment by mclemente** [comment]
Fixed on https://github.com/mclemente/party-overview/commit/114a6327801e75fffc5a209ff44b62429c5fbb0c.

**Comment by ditzer252** [comment]
Thank you!

**Comment by ditzer252** [comment]
Hi Matheus

The new Skills tab is fantastic and I find it really useful.  Would you consider also swapping the rows/columns for the other tabs?  I'm not making this a "new" issue, but I think it would improve overall usability.   Anyway, thanks again!
