### ISSUE TITLE
Wealth values do not scale by width and are too tight for values that can go into hundreds of thousands

### ISSUE THREAD

**Issue by apoapostolov** [mclemente/party-overview#18]
![image](https://user-images.githubusercontent.com/4083812/147893182-2dbb2e9f-c272-48a0-9247-a1f8378063a8.png)

**Comment by mclemente** [comment]
Should be better on the next release, check it out.

**Comment by mclemente** [comment]
Where's what it'll look like in 2.5.23, with nearly the same width as the print and roughly the same values:
![image](https://user-images.githubusercontent.com/5288872/148995756-d88c8682-c856-4466-8d0e-6cd80852f32f.png)

And here's the window at the default width:
![image](https://user-images.githubusercontent.com/5288872/148995852-a61312f0-b186-43e9-a1f1-bb6b20ab6dc3.png)

Hope this fixes the issue.
