### ISSUE TITLE
[System Request] Scum and Villainy

### ISSUE THREAD

**Issue by brunocalado** [mclemente/party-overview#19]
Hi. Can you add support for Scum and Villainy?

Character Actor Sheet
**Stress**
  "data": {
    "stress": {
      "value": "0",
      "max": 6,

**Creds**
  "data": {
    "coins": "0",

Ship Actor Sheet
**Creds**
  "data": {
    "gambits": {
      "max": 8,
      "value": "1"
    },

tks

**Comment by brunocalado** [comment]
Não sei por que não funciona para mim. 
Tentei desligar os outros modulos. Chrome. Win 10. Self hosted.

![image](https://user-images.githubusercontent.com/4999783/148438228-8024dc55-d664-4e25-8db3-dfa4f765b545.png)

**Comment by mclemente** [comment]
O personagem tem dono e está em algum mapa? O módulo só pega as informações de personagens no mapa.

**Comment by brunocalado** [comment]
> O personagem tem dono e está em algum mapa? O módulo só pega as informações de personagens no mapa.
Vacilo. Foi.

Ele aplica efeitos de outras camadas. É possível só aparecer o da camada que tem?
![image](https://user-images.githubusercontent.com/4999783/148445633-d494faa9-e833-4485-9382-48ede504b410.png)

Tripulação se refere a Qualidade na verdade. Acho que vou até mudar isso na tradução do scum da ficha. As informações mais importantes durante o jogo são Qualidade e Gambitos. Não sei se precisa cred, se quiser deicar move ele para ultima coluna por vafor.
![image](https://user-images.githubusercontent.com/4999783/148445807-1b85642e-0654-4f6c-bc9d-a2a0df015296.png)
