### ISSUE TITLE
[5e] party overview automically converts currencies

### ISSUE THREAD

**Issue by DarKDinDoN** [mclemente/party-overview#2]
Hello,

While it's not a bug, it feels weird to have Party Overview not actually displaying the current actor currencies.

![image](https://user-images.githubusercontent.com/1687854/130615466-9af54660-9c4c-4424-8a69-7198539d6ede.png)

⏫ In this example the character has:
- 0 PP
- 10 GP
- 0 EP
- 10 SP
- 0 CP

But party overview automatically converts it into:
- 1 PP
- 1 GP
- EP
- 0 SP
- 0 CP

While both are true, and the total amount is true as well, Party Overview doesn't really reflect what the character has in terms of currencies.

Maybe, make it a setting? So we can enable/disable this automatic conversion?

**Comment by mclemente** [comment]
That's actually a bug, it is converting the currencies.
