### ISSUE TITLE
Feature Request: SWADE: Update overview button

### ISSUE THREAD

**Issue by JasonSK22** [mclemente/party-overview#21]
Hello!

Great tool!  Would it be possible to have an update overview button a gm could activate when players toggle active effects.  Some AEs increase armor and it would be good to see these increases with out having to shut down and reload the overview.

Thanks for your great work!

**Comment by mclemente** [comment]
How odd, that's how it works for most systems already. I'll take a look at it.

**Comment by JasonSK22** [comment]
Here's a video of what I am experiencing.  This is in SWADE 0.22.5 with no other modules active except My Shared Compendia and Party Overview.  I am on Foundry 9.242

https://user-images.githubusercontent.com/28511333/148963957-6e8dddf2-c7c4-464a-be54-01dcfc9d206f.mp4

**Comment by mclemente** [comment]
This is embarrassing, but easy to fix. I overlooked the possibility that a system wouldn't default a PC's `Link Actor Data` to on, so I never set a hook to update the window.
