### ISSUE TITLE
Possible clash with Loot Sheet NPC 5e module?

### ISSUE THREAD

**Issue by Heljspe** [mclemente/party-overview#25]
I get this error when trying to open Party Overview?
'Party Chest' is a loot sheet that is only on the Landing Page (makes no difference if this is the active scene or not). 
Not sure though, because error still occurred when I turned that module off. 
![image](https://user-images.githubusercontent.com/68180128/149920825-fe5440fc-fc01-4903-b11b-08def486cb7a.png)

Foundry v9
D&D 5e v1.5.7

**Comment by mclemente** [comment]
I forgot NPCs don't have tool proficiencies and haven't tested with one being owned by the players.
