### ISSUE TITLE
The Party Overview Button isn't working and throws an error

### ISSUE THREAD

**Issue by tagnullde** [mclemente/party-overview#27]
This seems to be present in the last 2 Versions. I had this problem, updated all modules (party-overview received an update a couple of minutes ago on my install) but the error persists.

![image](https://user-images.githubusercontent.com/44159008/149977667-f8fecbac-9795-4f41-8e8c-a561504f5e33.png)

**Comment by mclemente** [comment]
Sorry, it should be fixed now.
