### ISSUE TITLE
NPC-type Actors Owned by a Player Throw an Error

### ISSUE THREAD

**Issue by 13FriendlyAI** [mclemente/party-overview#29]
This is for D&D5e version 1.5.7, Foundry is on version 9.

Last night I couldn't get Party Overview to open on select scenes in my world. After doing some tests I found it was scenes with specific tokens on them that were causing the issue: if a token uses the NPC actor type but is owned by a player (in this specific case it's the wizard's familiar "Wighead") that owned NPC token can't be read by Party Overview, causing the error.

Below is Foundry's console output to my bowser:

![Party Overview - 2022-JAN-20](https://user-images.githubusercontent.com/18380786/150382610-01c302cf-327c-4c46-8388-17f90d55bbc3.jpg)

I think the 2nd error is Foundry complaining that Party Overview's trying to read a variable with null value.

**Comment by mclemente** [comment]
Which module version are you on? If it's 2.7, that bug has already been fixed.

**Comment by 13FriendlyAI** [comment]
It is indeed version 2.7.

**Comment by 13FriendlyAI** [comment]
UPDATE: whilst Foundry claimed I was running version 2.7, after I checked for updates it seems to have fixed itself (even though it didn't download anything)

isn't technology great when it works? have a good day!
