### ISSUE TITLE
bug: Can't open party overview on old pf2e worlds on module versions greater than 2.6

### ISSUE THREAD

**Issue by xdy** [mclemente/party-overview#31]
See https://discord.com/channels/170995199584108546/697845559435853865/934429580780007444
Copied image of error one user gets below:
![image](https://user-images.githubusercontent.com/246024/150639967-2295075b-6f5d-41f6-a323-112ee430ab25.png)

On my forge world I don't get an error, but party overview won't open until I reverted to version 2.6
So, I'm guessing it's related to the new show skills feature for pf2e.

Familiars, loot actors and player-owned npcs need special handling in
https://github.com/mclemente/party-overview/blob/8b97d0473c26e5c93c77d57502710da82cfb8a13/module/SystemProvider.js#L595
To get at familiar skills, follow data.master.id and use their skills. (Or, maybe, just don't show skills for familiars).
Loot actors can safely be shown as having no skills.
Not sure what the issue with player-owned npcs is. The one in question has no skills, so maybe it's that?

**Comment by mclemente** [comment]
Should be fixed now.

**Comment by xdy** [comment]
Works fine, thanks!
