### ISSUE TITLE
System Request: 13th Age/Toolkit13

### ISSUE THREAD

**Issue by Flame11235** [mclemente/party-overview#32]
I would appreciate if you could add support for the 13th Age system: https://gitlab.com/asacolips-projects/foundry-mods/archmage

Being able to see HP, Defenses, Recoveries, and Icon Relationships in particular would be useful.

**Comment by mclemente** [comment]
Do characters have different icons among themselves or it's just a setting thing?

**Comment by mclemente** [comment]
And how exactly should the info be displayed? Relationship + Bonus, or just one of them?

**Comment by Flame11235** [comment]
For context an Icon is a powerful NPC/faction that a character has a relationship with. These are tracked in a few different ways, they have a strength (either 1, 2, or 3) as well as a nature of the relationship (either positive, conflicted, or negative) and in each session, a player might have one or more "5" benefits, or "6" benefits that they/the GM can spend to influence the story, or no benefit at all. Different characters can have different and independent relationships with icons and they can have anywhere from 2-5 relationships total. It looks like this in the character sheet and I think this is a good way of handling it? 

![image](https://user-images.githubusercontent.com/99065711/152672104-50ec9734-87ba-4387-a381-5da9cd82b4a2.png)

I just noticed in some of the other screenshots for this module that tabs are possible. So maybe the "General" tab could have HP, Recoveries (remaining and total, somewhat like 5E hit dice), AC, PD, and MD (3 defenses). An "Icons" tab could have the relationship stuff mentioned previously and a "Backgrounds" tab could show everyone's backgrounds (sort of a freeform skill system with numerical ratings, looks like this on the character sheet: 
![image](https://user-images.githubusercontent.com/99065711/152672319-3a5f7002-7396-4963-b8d6-ad9f629b495a.png)

Hopefully that makes sense, I'm not sure exactly what information you need. Please let me know if I can provide any more assistance.

**Comment by mclemente** [comment]
That's enough info. I needed to know if there could be 5+ icons per game, so the table would be better transposed.

Here's an example:
![image](https://user-images.githubusercontent.com/5288872/152694616-6fdb2b34-256d-424e-a49c-62b1cb290598.png)

Backgrounds will look more standard, like this:

| Name | 
|---|---|
| a | Shadow Port (+5), Magical Auras (+3)

**Comment by Flame11235** [comment]
I think that looks good except, for each Icon associated with a PC, it's important to know if they still have an icon benefit to spend. In the screenshot I posted, I have a "5" to spend with the Shadow Prince, and a "6" to spend with The Three.

**Comment by Flame11235** [comment]
Also, not sure if this matters for the backgrounds tab: characters have a minimum of 2 backgrounds but you could theoretically have like 20 if you built your character in a really weird way. I wouldn't expect most people to have more than, say, 5 though. But it can easily be a different number for different characters.

**Comment by mclemente** [comment]
Update and check it out.

**Comment by Flame11235** [comment]
Looks great! Thank you very much.
