### ISSUE TITLE
Filters aren't toggling properly

### ISSUE THREAD

**Issue by infias** [mclemente/party-overview#33]
When I open the party overview and click the eyes or filter in the top bar, it does not work properly to switch views or update the status of the actors in the view.

Foundry version 9 build 249
DnD5e version 1.5.7

![image](https://user-images.githubusercontent.com/88762169/154420361-3dc8a911-1a14-4f7b-9446-bbd6db0c112a.png)
![image](https://user-images.githubusercontent.com/88762169/154420439-34e2a6bd-078d-4e39-8b29-a32757419b8f.png)

**Comment by mclemente** [comment]
Are you on the latest version? I can't reproduce this and a similar issue was fixed some time ago.

**Comment by infias** [comment]
Latest Foundry and Party Overview and just tried uninstalling the module and reinstalling to the same effect. I have my server up, and you can use the "player" account with no password to see what is going on. If you need more permissions, I can grant them.

http://infias.mynetgear.com/

![image](https://user-images.githubusercontent.com/88762169/154541086-addaeadb-2e0d-460a-bfff-94a5dceff1b7.png)

**Comment by mclemente** [comment]
Thanks for the link, that helped a lot!

**Comment by infias** [comment]
Sweet! I look forward to the patch; I'm glad to help out.
