### ISSUE TITLE
Feature Request: Toggle only showing players active in scene.

### ISSUE THREAD

**Issue by CKarper** [mclemente/party-overview#37]
I love being able to use the party overview as the DM, but we frequently use scenes as reference overland maps, and the players don't have active tokens there.  I'd love to be able to always see my player's overview even when they're not active on my current scene.

**Comment by mclemente** [comment]
If you click twice over the Filter Button (the one besides "Name"), you'll get all owned characters in the game despite the scene. Is that what you're looking for or are you looking for something different?

**Comment by CKarper** [comment]
That's exactly what I was looking for.   Closing this issue, thank you!

**Comment by CKarper** [comment]
Well, after playing with this.. it's kind of an all or nothing filter.  It would be great to have a checkbox for "active in scene" only or something, so I can still use the "hide actor" toggles.
