### ISSUE TITLE
[SFRPG] reflex/fort/save showing 0 vice actual bonus

### ISSUE THREAD

**Issue by pbeldridge** [mclemente/party-overview#47]
[SFRPG] Unable to get module to show saving throw bonuses in General tab (see attached picture).  Tested with all modules but Party Overview deactivated.
![saving throws](https://user-images.githubusercontent.com/1688284/179868499-ece76940-abb3-4b29-a975-182865dec888.png)
![party saves](https://user-images.githubusercontent.com/1688284/179868626-50e88216-ecfa-43c7-b373-4445e5da6b23.png)
.

**Comment by mclemente** [comment]
Hm, the actual value for the saves is `bonus`, while everything else but skills use `value`.

**Comment by mclemente** [comment]
This should be fixed on version 2.13.3.
