### ISSUE TITLE
5th party member won't show

### ISSUE THREAD

**Issue by redaxe11** [mclemente/party-overview#51]
I can't get my 5th party member to show. It shows 4 of them but not the 5th. They are 100% Owned by a player in the permissions. Any ideas?

**Comment by mclemente** [comment]
Any errors on the console? Was the character selected by the player (i.e. the character's name shows up right by the player's name on the player's list on the bottom left)?

**Comment by redaxe11** [comment]
Fixed. It was the character hadn't been selected by the player and the default view was "All Selected". When I changed it to All then the 5th character appeared and when I logged in as the user and "selected" the character on login then it also appeared.

Thanks
