### ISSUE TITLE
[BUG] Always Updating

### ISSUE THREAD

**Issue by 9ryex5** [mclemente/party-overview#54]
This module seems to always be updating versions despite staying the same.
![image](https://user-images.githubusercontent.com/43207603/188458964-365610aa-c739-4ade-9d60-7b0854f3aaa0.png)
![image](https://user-images.githubusercontent.com/43207603/188459004-db95811a-5430-4996-8a19-047117cecb41.png)

**Comment by mclemente** [comment]
Damn, it is `https` when installed but the link is listed as `http` on the package on Foundry. Issue should be fixed now.
