### ISSUE TITLE
Pf2e - special languages not shown on the party overview->languages page

### ISSUE THREAD

**Issue by DawidIzydor** [mclemente/party-overview#60]
I have a PC with _Iobarian_ language added as special language. It is not showing up on the languages page inside the party overview. Special/custom langauges should be visible in the party overview page

![obraz](https://user-images.githubusercontent.com/30767613/209634165-a079cc4b-3fc4-46e2-bdd9-6170b55a5285.png)

**Comment by mclemente** [comment]
Should be fixed now. Reminder that you can add new languages to PF2e through its Homebrew Elements setting instead of depending on the Special entry.
