### ISSUE TITLE
dnd5e - Party overview won't display due to languages error.

### ISSUE THREAD

**Issue by CKarper** [mclemente/party-overview#61]
## Env
**Module:** party-overview v2.15.7
**System:** dnd-5e v2.1.2
**VTT:** Foundry v10.291
**Browser:** Chrome v108.0.5359.125 (Official Build) (64-bit)

## Description

There is no response when clicking the `Party Overview` in the VTT, but the console shows the following error.

```
foundry.js:747 TypeError: actor.languages.includes is not a function
[Detected 1 package: party-overview]
    at SystemProvider.js:604:79
    at Array.map (<anonymous>)
    at SystemProvider.js:604:26
    at Array.map (<anonymous>)
    at dnd5eProvider.getUpdate (SystemProvider.js:601:19)
    at PartyOverviewApp.update (logic.js:61:45)
    at PartyOverviewApp.getData (logic.js:112:8)
    at PartyOverviewApp._render (foundry.js:5108:29)
    at PartyOverviewApp.render (foundry.js:5067:10)
    at PartyOverviewApp.render (logic.js:159:9)
    at HTMLButtonElement.<anonymous> (party-overview.js:62:17)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
```
![image](https://user-images.githubusercontent.com/653156/212499339-8a73f09c-e8a3-4c26-8648-3895edf808c6.png)

**Comment by CKarper** [comment]
![image](https://user-images.githubusercontent.com/653156/212499713-1d0c022f-88ef-4f1c-a757-17fb866644c8.png)

**Comment by CKarper** [comment]
Perhaps an API has changed, `actor.languages` appears to be a `Set`, not an array.  

[`.has`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/has) instead?

**Comment by CKarper** [comment]
OK, so, either convert to array, or change to use `Set` all the way through.

![image](https://user-images.githubusercontent.com/653156/212499945-0fa4346e-402d-4769-8fe5-77da3ff77e10.png)

**Comment by CKarper** [comment]
I have to prep for my session now, I can't track this down anymore.  Thanks for considering this!

**Comment by mclemente** [comment]
dnd5e's 2.1 update changed all Traits' data from Array to a Set, so it broke Languages and Tools. Thank you for all the debugging.

**Comment by mclemente** [comment]
Should be fixed now.

**Comment by CKarper** [comment]
Even done in time for tonight's session, thank you!
