### ISSUE TITLE
Not working anymore in Tormenta20

### ISSUE THREAD

**Issue by WanderSiqueira** [mclemente/party-overview#65]
I'm using Party Overview in my table for months, and it stopped working couple weeks ago.

**Comment by mclemente** [comment]
Tem algum erro no console (F12) relacionado ao módulo? Testei aqui num mundo novo de T20 e funcionou normalmente.

**Comment by WanderSiqueira** [comment]
Fala, meu chefe.

Tem esse erro aqui:
![image](https://user-images.githubusercontent.com/80720153/227341630-6eb572bb-7fb5-4305-923a-cc9ee7c46a42.png)

Pode ser que o problema seja comigo (se for, me dá uma dica aí de como resolver, por favor kkkkk)

**Comment by mclemente** [comment]
Esse erro quer dizer que tá faltando um arquivo, sendo que não mudei nada no caminho dos arquivos.
Não sei como aconteceu, mas se você reinstalar o módulo deve resolver.

**Comment by mclemente** [comment]
Fechando, pois não há o que ser resolvido..
O arquivo da mensagem de erro não foi modificado desde Dezembro/2021 e é essencial em todos os sistemas. Se fosse um erro com o módulo, teria vários tickets abertos sobre isso.
