### ISSUE TITLE
UPDATE: Change Default Filter button to All Scene Unfiltered

### ISSUE THREAD

**Issue by Baxmann** [mclemente/party-overview#70]
UPDATE: I have discovered what the issue was. The module has different filter modes that show or hide what's visible. For some reason ALL SELECTED, even when having tokens selected and targeted don't update and show up. 
All Scene Unfiltered should be the default to avoid confusion. 
![Screenshot 2023-07-02 150524](https://github.com/mclemente/party-overview/assets/34702584/d8746268-5d5b-4e8b-9314-8a0901596215)

**Comment by mclemente** [comment]
Is the character assigned to the player? If they are, does the character shows up when changing filters, most specifically the "All" filter?

**Comment by rtfmtech** [comment]
I am also having this issue, I am logged in as the GM, players and tokens are set to Owner, not showing up on the list, no matter which filter I use

**Comment by mclemente** [comment]
Are there any errors on the console? I don't have that issue on a brand new world, so I'm not sure what is wrong here.

**Comment by rtfmtech** [comment]
So, oddly enough, it's working now.. not sure which of these steps fixed it,, but I made a second account as a "watcher" and removed all the characters I currently had, then recreated one, set the permissions to Owner  for everyone,  then it's showing up.

**Comment by mclemente** [comment]
>For some reason ALL SELECTED, even when having tokens selected and targeted don't update and show up.

All Selected means all characters assigned to a user (e.g. the character name shown on the player list alongside their user).
