### ISSUE TITLE
Does Not Work w/ v11

### ISSUE THREAD

**Issue by kajishun** [mclemente/party-overview#74]
Forge VTT lists this as compatible with v11. It does not work. Please update the Compatible Core Version to reflect this.

**Comment by mclemente** [comment]
The module does work on V11. Which system are you on?

**Comment by kajishun** [comment]
Hmm, interesting. I am on DnD5e 2.3.1 & FVTT v11.309. I tried FTC with only
Party Overview enabled. Party Overview does not start. I see console errors
screenshotted below.

[image: image.png]

**Comment by mclemente** [comment]
Your reply through email has no image (both on email and on github), send it again through Github.

**Comment by kajishun** [comment]
![image](https://github.com/mclemente/party-overview/assets/60208624/db0648f1-3fce-4643-851a-fd6e78833621)

**Comment by kajishun** [comment]
did you find a problem? is there a fix to be implemented?

**Comment by mclemente** [comment]
Yes, just update and it should work now.

**Comment by kajishun** [comment]
I tried it just now and it works. Except it is not picking up tool
proficiencies. Yay, thank you! BTW, I recommend rearranging it so party
members are always on the vertical or horizontal. Switching it up for
Proficiencies is hard to read. But if all tabs were aligned that way, it
would be ideal. Thank you again for this awesome FVTT module!
