### ISSUE TITLE
Not working in Forged in the Dark system

### ISSUE THREAD

**Issue by cojoMan** [mclemente/party-overview#78]
I have several characters, created players, assigned characters, but cannot see any in the party overview.
Foundry 11.313 Stable, Blades in the Dark system 4.8

![Screenshot 2023-10-27 110150](https://github.com/mclemente/party-overview/assets/4105124/786a3b3b-e838-436e-a6dc-340e9dd1b178)

**Comment by mclemente** [comment]
>assigned characters

Have your players selected those characters like in this image?

![image](https://github.com/mclemente/party-overview/assets/5288872/92d46407-1029-44b2-9aea-69884275f922)

Does no character shows up when the filter is set to `All` (All Owned)?

**Comment by cojoMan** [comment]
ah ! 
they did come into the game but they didn't click on the character to claim it. Tried now with 3 of them and it's there
thank you !

![Screenshot 2023-10-27 131907](https://github.com/mclemente/party-overview/assets/4105124/b08186e0-187f-4b0c-8882-3c0d56fa50bf)
