### ISSUE TITLE
Feature request: Total Wealth PF2

### ISSUE THREAD

**Issue by jpmiers** [mclemente/party-overview#8]
I love this mod and use it constantly.
It would be helpful to add a an extra column under the wealth tab that should the total wealth (including value of items in inventory). It's helpful for estimating loot rewards. I know it wouldn't be completely inclusive due to not calculating money spent on services/spells but it'd help.
Thanks for all you do!

**Comment by mclemente** [comment]
Does this looks good enough?
![image](https://user-images.githubusercontent.com/5288872/133705152-41cc1817-7ff8-495e-8ef8-7e1df52275a1.png)

**Comment by mclemente** [comment]
It's on the next update, check it out!
