### ISSUE TITLE
Feature Request: GM Choose info to display

### ISSUE THREAD

**Issue by Heljspe** [mclemente/party-overview#9]
Hi, 

Would love the ability to choose which information showed up in the party overview (at a GM level for all players). 
For example, our backgrounds are a secret in the current campaign, so would love to be able to turn just that tab off, but keep the others. 
I'd prob choose to just have Languages in my game tbh, if I could choose, as I have other mods for everything else :)

**Comment by mclemente** [comment]
Hey, I've finally figured a way that works for any supported system, so expect this feature on the next update (unless I need to fix something in-between).

**Comment by Heljspe** [comment]
Awesome! Thank you!!

**Comment by mclemente** [comment]
Could you try installing this over your Party Overview folder to test it? https://github.com/mclemente/party-overview/archive/refs/heads/Info-Display-Testing.zip

Just move its contents into the party-overview folder and overwrite everything. The choice to change the tabs should show up on the Party Overview System Settings menu.
